name: teste_tflow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  camera: ^0.11.0+1
  flutter:
    sdk: flutter
  flutter_tflite: ^1.0.1
  get: ^4.6.6
  image: ^3.3.0
  permission_handler: ^11.3.1
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:

    - assets/


